import './globals.css';

import { Analytics } from '@vercel/analytics/react';

import { SiteHeader } from '@/components/site-header';
import { ThemeProvider } from '@/components/theme-provider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="min-w-screen flex min-h-screen flex-col bg-dotted-spacing-4 bg-dotted-gray-200 dark:bg-dotted-gray-900">
          <ThemeProvider attribute="class" defaultTheme="light">
            <SiteHeader />
            {children}
            <Analytics />
          </ThemeProvider>
        </main>
      </body>
    </html>
  );
}
